### ISSUE TITLE
Data file

### ISSUE THREAD

**Issue by virajt71** [mjkmoynihan/kinectPointCloudICP#1]
can u plz share this data file "DCU_desk_xyz.mat"??

**Comment by mjkmoynihan** [comment]
Unfortunately I don't have access to this data anymore as it was at my old lab but if you have access to a kinect for windows (v1 definitely works, v2 is untested) you should be able to run the code and capture new data. 

Alternatively you can also run the code on some existing benchmarks such as the Freiburg RGB-D datasets: 
https://vision.in.tum.de/data/datasets/rgbd-dataset/download
You'll just have to convert the pngs into mat format for MATLAB.

**Comment by virajt71** [comment]
I don't have access to kinect. But i will try alternatively way.
Ty for fast reply
